Repository ansible/eda-server, pull requests merged in 2024-08, with the labels that each got.

#983 chore(AAP-28384) ensure psycopg v3 dependency
  poetry.lock
  pyproject.toml
Labels: run-e2e

#988 fix(AAP-27994): update import status to completed on empty project
  src/aap_eda/services/project/imports.py
  src/aap_eda/services/project/scm.py
  tests/unit/test_scm.py
Labels: run-e2e

#989 AAP-27921 Use DAB-provided Redis client.
  poetry.lock
  pyproject.toml
  src/aap_eda/core/tasking/__init__.py
  src/aap_eda/settings/default.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/core/test_tasking.py
Labels: run-e2e

#982 feat(AAP-28111): add more managed roles on object and org levels
  src/aap_eda/core/management/commands/create_initial_data.py
  tests/integration/core/test_create_initial_data.py
Labels: run-e2e

#984 feat: (AAP-28247) - add endpoint to fetch Activations by event streams
  src/aap_eda/api/filters/__init__.py
  src/aap_eda/api/views/webhook.py
  src/aap_eda/core/migrations/0043_alter_activation_webhooks.py
  src/aap_eda/core/models/activation.py
  tests/integration/api/test_activation_with_webhook.py
Labels: run-e2e

#986 feat: (AAP-28246) - only delete the event stream when no activations using it
  src/aap_eda/api/views/webhook.py
  tests/integration/api/test_webhook.py
Labels: run-e2e

#996 fix: add generation of unix url for DAB redis client
  src/aap_eda/core/tasking/__init__.py
  tests/integration/core/test_tasking.py
Labels: run-e2e

#993 feat: (AAP-28235) - Add source mappings to event streams
  src/aap_eda/api/constants.py
  src/aap_eda/api/serializers/activation.py
  src/aap_eda/core/migrations/0044_remove_activation_swap_single_source_and_more.py
  src/aap_eda/core/models/activation.py
  src/aap_eda/core/utils/rulebook.py
  src/aap_eda/core/utils/strings.py
  tests/integration/api/test_activation_with_webhook.py
  tests/integration/api/test_rulebook.py
  tests/integration/core/test_rulebook.py
Labels: run-e2e

#997 feat (AAP-29049) - before deleting credentials check if event streams attached
  src/aap_eda/api/serializers/eda_credential.py
  tests/integration/api/test_eda_credential.py
Labels: run-e2e

#998 feat: AAP-28915 option to skip audit events
  src/aap_eda/api/serializers/activation.py
  src/aap_eda/core/migrations/0045_activation_skip_audit_events.py
  src/aap_eda/core/models/activation.py
  tests/integration/api/test_activation.py
  tests/integration/conftest.py
Labels: run-e2e

#999 fix(AAP-29090): remove member_organization permission from org admin role
  src/aap_eda/core/management/commands/create_initial_data.py
  tests/integration/conftest.py
  tests/integration/core/test_create_initial_data.py
  tests/integration/dab_rbac/test_managed_roles.py
Labels: run-e2e

#1000 AAP-27923: implement EDA HA Cluster Redis support.
  poetry.lock
  src/aap_eda/core/tasking/__init__.py
  src/aap_eda/settings/default.py
  src/aap_eda/tasks/orchestrator.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/core/test_tasking.py
  tools/docker/docker-compose-dev-redis-tls.yaml
  tools/docker/docker-compose-dev.yaml
  tools/docker/docker-compose-mac.yml
  tools/docker/docker-compose-stage.yaml
Labels: run-e2e

#1001 fix: check for valid settings before creating EventStreams
  src/aap_eda/core/validators.py
  src/aap_eda/settings/default.py
  tests/integration/api/test_webhook.py
  tests/integration/dab_rbac/test_crud_permissions.py
  tests/integration/dab_rbac/test_organization.py
Labels: run-e2e

#1005 feat: Add CRUD log messages
  .gitignore
  src/aap_eda/api/views/activation.py
  src/aap_eda/api/views/decision_environment.py
  src/aap_eda/api/views/project.py
  src/aap_eda/api/views/webhook.py
  src/aap_eda/core/utils/logging_utils.py
Labels: run-e2e, 3ci-debug

#1009 Redis ha/aap 28151
  poetry.lock
  src/aap_eda/api/views/mixins.py
  src/aap_eda/api/views/project.py
  src/aap_eda/core/tasking/__init__.py
  tests/integration/api/test_project.py
Labels: run-e2e

#1012 Redis ha/aap 28152
  src/aap_eda/api/views/activation.py
  src/aap_eda/core/models/activation.py
  tests/integration/api/test_activation.py
Labels: run-e2e

#1007 fix(AAP-29089): change organization field to be required in RBAC managed resources
  src/aap_eda/api/serializers/activation.py
  src/aap_eda/api/serializers/decision_environment.py
  src/aap_eda/api/serializers/eda_credential.py
  src/aap_eda/api/serializers/project.py
  src/aap_eda/api/serializers/team.py
  src/aap_eda/api/serializers/webhook.py
  src/aap_eda/core/migrations/0046_alter_activation_organization_and_more.py
  src/aap_eda/core/models/base.py
  tests/integration/api/test_activation.py
  tests/integration/api/test_activation_with_credential.py
  tests/integration/api/test_activation_with_webhook.py
  tests/integration/api/test_eda_credential.py
  tests/integration/api/test_k8s_activation.py
  tests/integration/api/test_project.py
  tests/integration/api/test_webhook.py
  tests/integration/conftest.py
  tests/integration/dab_rbac/test_organization.py
Labels: run-e2e, run-ui-e2e

#1014 fix: return kwargs from _prune_redis_kwargs
  src/aap_eda/core/tasking/__init__.py
Labels: run-e2e

#1015 chore: add 'restart: always' to scheduler in compose files
  tools/docker/docker-compose-dev-redis-tls.yaml
  tools/docker/docker-compose-dev.yaml
  tools/docker/docker-compose-mac.yml
  tools/docker/docker-compose-stage.yaml
Labels: run-e2e

#1016 fix: (AAP-29630) - save extra_var when creating an activation with vault/AAP credentials
  src/aap_eda/api/serializers/activation.py
  tests/integration/api/test_activation_with_credential.py
  tests/integration/conftest.py
Labels: run-e2e, run-ui-e2e

#1019 fix: perform project create request validation before redis check
  src/aap_eda/api/views/project.py
  tests/integration/api/test_project.py
Labels: run-e2e

#1013 feat: (AAP-29121) - Remove force deletion on credentials when event streams use it
  src/aap_eda/api/serializers/eda_credential.py
  src/aap_eda/api/views/eda_credential.py
  tests/integration/api/test_eda_credential.py
Labels: run-e2e

#1021 fix: (AAP-29642) - Fix to save encrypted string in credentials
  src/aap_eda/api/views/eda_credential.py
  src/aap_eda/core/utils/credentials.py
  tests/integration/api/test_eda_credential.py
Labels: run-e2e

#1022 fix: (AAP-29719) - enable verify_ssl to skip ssl verify during pulling image from registry
  src/aap_eda/services/activation/activation_manager.py
  src/aap_eda/services/activation/engine/common.py
  src/aap_eda/services/activation/engine/exceptions.py
  src/aap_eda/services/activation/engine/podman.py
  tests/integration/services/activation/engine/test_kubernetes.py
  tests/integration/services/activation/engine/test_podman.py
Labels: run-e2e

#1020 feat: (AAP-29728) - Add ruleset_stats to activation read view
  src/aap_eda/api/serializers/activation.py
  tests/integration/api/test_activation.py
  tests/integration/wsapi/test_consumer.py
Labels: run-e2e

#1023 chore(AAP-29868): add new vars related to roles
  src/aap_eda/settings/default.py
  tools/docker/docker-compose-dev-redis-tls.yaml
  tools/docker/docker-compose-dev.yaml
  tools/docker/docker-compose-mac.yml
  tools/docker/docker-compose-stage.yaml
Labels: run-e2e

#1025 fix: (AAP-29615) 500 error when creating a credential with a none credential type id
  src/aap_eda/api/serializers/eda_credential.py
  tests/integration/api/test_eda_credential.py
Labels: run-e2e

#1028 fix(AAP-29951): add summary_fields for event stream model
  src/aap_eda/core/migrations/0049_alter_eventstream_name.py
  src/aap_eda/core/models/event_stream.py
Labels: run-e2e

#977 feat: implement a customized jwt authentication for websocket login
  poetry.lock
  pyproject.toml
  src/aap_eda/api/authentication.py
  src/aap_eda/api/serializers/__init__.py
  src/aap_eda/api/serializers/auth.py
  src/aap_eda/api/urls.py
  src/aap_eda/api/views/__init__.py
  src/aap_eda/api/views/auth.py
  src/aap_eda/services/auth.py
  src/aap_eda/services/exceptions.py
  src/aap_eda/settings/default.py
  tests/integration/api/test_auth.py
  tests/integration/services/test_auth.py
Labels: run-e2e

#1029 chore: Create and POST jUnit results file
  .github/workflows/ci.yaml
  .github/workflows/e2e-dispatch.yml
  .gitignore
  poetry.lock
  pyproject.toml
Labels: run-e2e

#1031 fix: (AAP-30118) - remove awx token from error message
  src/aap_eda/api/serializers/activation.py
  tests/integration/api/test_activation.py
  tests/integration/api/test_activation_with_credential.py
  tests/integration/services/activation/test_manager.py
Labels: run-e2e
